## Let's read the spreadsheet and see what we've got

In [1]:
import pandas as pd

In [3]:
fname = '../input_data/OF8619_SpectralLibrary_OneHot.xlsx'
df = pd.read_excel(fname, None)
sheets = list(df.keys())  # see all sheet name

# This concatenates everything back into a single sheet. 
# We can do this because all sheets have the same rows. And the
# Data is well-behaved.
dfs = [pd.read_excel(fname, sheet) for sheet in sheets]
df = pd.concat(dfs)

df.to_csv('one_hot_set_of_minerals.csv')

In [4]:
df

,Sample,Mineral Group,TGI6 Focus,400-900 Albedo,585 nm Min,640 nm Min,685 nm Min,745 nm Min,800 nm Min,870 nm Min,...,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135
0,Agardite_NMC063729_2278,Arsenates,NaN,0.0379,NaN,NaN,NaN,NaN,813.73,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Goudeyite_NMC019652_2280,Arsenates,NaN,0.1500,NaN,NaN,NaN,NaN,804.64,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Agardite_NMC064423_2279,Arsenates,NaN,0.0914,NaN,NaN,NaN,746.07,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Braitschite_NMC017548_2163,Arsenates,NaN,0.0868,NaN,650.58,677.83,748.15,809.82,878.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Chernovite_NMC065122_2191,Arsenates,NaN,0.1580,591.66,652.65,NaN,757.58,808.80,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,Thorite_NMC062402_2328,Silicates,2.0,0.0919,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
484,Britholite-Ce_NMC067639_2343,Silicates,2.0,0.0254,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
485,Britholite_NMC018729_2339,Silicates,2.0,0.0681,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
486,Tritomite-Y_NMC014268_2357,Silicates,2.0,0.0846,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
487,Gadolinite_NMC015055_2347,Silicates,2.0,0.0696,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

One thing that is slightly odd, is that, because of the way the spreadsheet is formatted, some of the column names are `integers` some of them are `strings`. This is fine, but we might want to make them all strings.

For instance I can access the `978` column like so:

In [5]:
df[978]

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
483   NaN
484   NaN
485   NaN
486   NaN
487   NaN
Name: 978, Length: 5368, dtype: float64

So we can make all of the column names strings,

In [7]:
df.columns = df.columns.astype(str)

It is mostly "NaNs" (not a number), at the top and bottom, but don't be bothered by that.

In [10]:
# Now this gets us the same thing
df['978']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
483   NaN
484   NaN
485   NaN
486   NaN
487   NaN
Name: 978, Length: 5368, dtype: float64

In [17]:
# 
def decision_tree(row):
    """
    takes a dictionary called `row`, and asks a series of 
    if questions to determine the mineral name
    
    Args:
        row (dict): a dictionary of 1s and zeros of key features
    
    Retruns:
        mineral (str): the mineral classification
    """
    if row['978']:
        if row['915']:
            if row['909']:
                mineral = 'Eudialyte'
            else:
                if row['911']:
                    mineral = 'Donnalyte'
                else:
                    if row['805']:
                        mineral = 'Kainosite or Xenotime'
        else:
            mineral = 'unknown'
            
    else:
        mineral = 'unknown'
    
    return mineral

Amazing!

But our predictions don't have a column that we can compare to one row as a time.

In [18]:
def make_name(value):
    return value.split('_')[0]

df['mineral_name'] = df['Sample'].apply(make_name)

In [19]:
len(sorted(df['mineral_name'].unique()))

118

In [20]:
sorted(df['mineral_name'].unique())

['Aeschynite',
 'Aeschynite-Ce',
 'Aeschynite-Y',
 'Agardite',
 'Allanite',
 'Allanite-Ce',
 'Allanite-Y',
 'Ancylite',
 'Apatite',
 'Bariopyrochlore',
 'Bastnsite',
 'Bastnsite-Ce',
 'Betafite',
 'Braitschite',
 'Brannerite',
 'Britholite',
 'Britholite-Ce',
 'Britholite-Y',
 'Brockite',
 'Burbankite',
 'Carbocernaite',
 'Carnotite',
 'Caysichite',
 'Cebaite-Ce',
 'Ceriopyrochlore',
 'Cerite',
 'Chernovite',
 'Chevkinite',
 'Chevkinite-Ce',
 'Chlorapatite',
 'Churchite',
 'Columbite',
 'Columbite-Tantalite',
 'Cordylite',
 'Davidite',
 'Epistolite',
 'Eudialyte',
 'Euxenite',
 'Fergusonite',
 'Fergusonite-Y',
 'Ferrocolumbite',
 'Fluocerite',
 'Fluorapatite',
 'Franconite',
 'Gadolinite',
 'Gadolinite-Ce',
 'Gagarinite',
 'Gerasimovskite',
 'Gittinsite',
 'Goudeyite',
 'Gysinite-Nd',
 'Hellandite',
 'Hibonite',
 'Hochelagaite',
 'Huanghoite',
 'Hydroxylapatite',
 'Iimoriite',
 'Ixiolite',
 'Kainosite',
 'Kalipyrochlore',
 'Lanthanite',
 'Lanthanite-Nd',
 'Latrappite',
 'Liebigite',
 'Lokkaite',
 'Loparite-Ce',
 'Loranskite-Y',
 'Lueshite',
 'Melanocerite',
 'Metatorbernite',
 'Metatyuyamunite',
 'Metauranocircite',
 'Microlite',
 'Miserite',
 'Monazite',
 'Monazite-Ce',
 'Monazite-La',
 'Mosandrite',
 'Murmanite',
 'Nenadkevichite',
 'Niobophyllite',
 'Parisite',
 'Perovskite',
 'Perrierite',
 'Polycrase',
 'Pyrochlore',
 'Rhabdophane',
 'Sahamalite',
 'Samarskite',
 'Samarskite-Y',
 'Schuilingite',
 'Simpsonite',
 'Steenstrupine',
 'Stibiotantalite',
 'Stillwellite',
 'Synchysite-Y',
 'Tanteuxenite',
 'Tapiolite',
 'Tengerite',
 'Tengerite-Y',
 'Thalenite',
 'Thalenite-Y',
 'Thorbastnsite',
 'Thorite',
 'Thortveitite',
 'Tombarthite',
 'Tritomite-Y',
 'Tundrite',
 'Uranpyrochlore',
 'Vitusite-Ce',
 'Vuonnemite',
 'Wakefieldite',
 'Whlerite',
 'Xenotime',
 'Yttrialite',
 'Yttropyrochlore',
 'Yttrotungstite',
 'Zircon']

In [21]:
df['Mineral Group'].unique()

array(['Arsenates', 'Carbonates', 'Halides', 'Oxides', 'Phosphates',
       'Silicates', 'Tungstates', 'Vanadanate'], dtype=object)

In [22]:
# It looks magical, but it basically applies our function across all the rows.
df['mineral_predicton'] = df.apply(decision_tree, axis=1)

In [23]:
# we can reorder the columns if we want to 
new_column_order = list(df.columns[-2:]) + list(df.columns[1:-2])
df_with_predictions = df[new_column_order]
df_with_predictions

,mineral_name,mineral_predicton,Mineral Group,TGI6 Focus,400-900 Albedo,585 nm Min,640 nm Min,685 nm Min,745 nm Min,800 nm Min,...,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135
0,Agardite,Eudialyte,Arsenates,NaN,0.0379,NaN,NaN,NaN,NaN,813.73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Goudeyite,Eudialyte,Arsenates,NaN,0.1500,NaN,NaN,NaN,NaN,804.64,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Agardite,Eudialyte,Arsenates,NaN,0.0914,NaN,NaN,NaN,746.07,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Braitschite,Eudialyte,Arsenates,NaN,0.0868,NaN,650.58,677.83,748.15,809.82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Chernovite,Eudialyte,Arsenates,NaN,0.1580,591.66,652.65,NaN,757.58,808.80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,Thorite,Eudialyte,Silicates,2.0,0.0919,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
484,Britholite-Ce,Eudialyte,Silicates,2.0,0.0254,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
485,Britholite,Eudialyte,Silicates,2.0,0.0681,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
486,Tritomite-Y,Eudialyte,Silicates,2.0,0.0846,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
487,Gadolinite,Eudialyte,Silicates,2.0,0.0696,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Now we can save this new CSV to a file.

In [24]:
df_with_predictions.to_csv('predictions.csv')